repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v0.0.2
    hooks:
      - id: pycln
        args:
          [
            --all,
            --exclude=(\.eggs|\.git|\.mypy_cache|__pycache__|__init__\.py),
          ]
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
